language: scala
scala: 2.12.7
jdk: openjdk8

stages:
  - name: test
  - name: publish
    if: NOT type = pull_request

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "i29GHPf3vcL+iAqQj0oapNItQaSsL8f21UfmIRUicGtU72utwc1h8tPTXUdGP+MLTMNJw90zPQItJ9hne/Yrc8F5X4AmXvY8aFILOb1+ZNIBaxjHcYq7j02xgR2tYEMcNzmdS9buPYvDK+PooCnBQxCi6QKpw3bm1c49g9pnnA2jCBZGUnQNKGLGNUkxR+j4Sp3tYhbq+sEDiMm5M9LF3yTs7npdMr6gVIGfuvhZcrUlAfmIqLUVSrAs6XvHDBPPUuFB9BJF6glYLyUA/N+PQl5DjfRO/AsLoUX4YBneonXlL6Qww9zBMEoQxuZDt1bQJ9AHd665uk6JT9S4op7Z/Z4VizRI59V/ZiPWVAyhxl/j/kP8lZbbXzH5cvZzDSmHmLmv4PeWZ2m5La4osUzL9NOkb5YZt89UrKQIEkBc1d1rrn5kwQ3tzfUMfS/zclzh5udpTo3zHsOg+5DURqmPsTNL9eM07zwdlx4FPhF9kgPkePV8wv3P8JBwN3vCNfeBJ6Npz3g+1V+rvjPW6Shx2cXdqSOwAY0Fb9hjhgmtB9gcYQzsfXYyd4hY95AsPVpOfnqwbNwfd0/nW2BP/BT8xz3cbIzdki7KXMnITtelA8aanGpgIpPNaXwKI2Z8rBodyem8MbjQ8v4CAR4fgB/kdWpVc8wmbJNL/WZEZd4Idog="
    # GITHUB_TOKEN
    - secure: "sjL5473U2HBnZKO8/LDckTZrwCOZe7TDqd0ie2WbschKLy3UqAYtR3/+qJK9IeQwpndTKsWoagFB9LWmhdK27RPXYqY9/QQ0+qqV3Vf0xd1QyE3BGBSWYxyr9aEMNHwJwzGU3rm2R08L1ntv82E3wQ9OC5dCbDgtRSJiurav61MEzHxsTQnWsqVSQsxJ/HKiafeGuO4bekRAF5vOteJklE9Co1d/tRVDv97tkC0QLMQJMpx/2Sy5zGfVVRiwNZFpGIMeY2DYo/5+RA0rW3RhkEsYuAiMJ5l5Admw9c+NeQ/YYcYGMJFsUWUTeBfxDhF3LeaLZ0c/sOSDnn5uNe3hslhfTbc6oBd/qAg4vNIsPr6IpKjMgIg0JRbiIkDXSePN2ybMm2MfqGhLTttE24gI/u24Aur+ju0CYkX6sgOzbGecNq45bcjQewbrglZGo6dnHcK/PvkxyVhh9xIB/kCYyphA0sjWjLd/9y6ycUX6JdGeEhBZJNePhvLQCDZj8CB4qBkhRIKdETllwylYsus4DUN0FXywKsRyBmatyH7ruxbjLLyClvOSLsaOms4aM6+vhx0kCyAc/NGN/A/9mosx7wxffi66XqupqJ/siJmWw9RbsdHvg3sqd3bF1moAgQrqdsepGHXzX6SjuGEc4y3rMSBCMzqevjMvg9xdYfBbWHc="
    # GITHUB_ACCESS_TOKEN
    - secure: "YjijPnwVwpZJO/wJHeFQxOWcK5gZwJHxhK+NOcf0C9eKqJY6wNkLIgyUj73woGw8PtJFS4BAVfz+qDcAyK0MjT9vG1XGsoPJuI/W+FazbXHH95gZSCt3fpbSRnvcW8Rj5X/7/x7WP2yab7pSgyVOYFvPC/dB+4nqyyIN8IIyct384dA7/u5guiBBKKSMJHfL5NjKEzRk3xw8e5FLVoTwHQ3wVMnmwK31fM00UQx+l8MrXtD0OsVNCq9fumJP3RsNq6nvCJKMC59to/P4f//QqcsCiraDqBZtIODc8O3DTofsWxE+8p9WstuV+X+UCHwy0Fy2QcxLSFBNgj6Vmou9dWvnEvzddz4GUfD0Aka7nToU25IjKBQVXymC99r9Hab+iWLvWox4S3/BLUMXQogMINWKkciNCQKKdwzZl98eigfmFLDch0MUNyKgOscHH8Sp4y+prQ/uDU9kLVAvA4hqUR7w+Z4ii4h2guD3OdAjoCbDZTFurpOGczxAHB+est976JfRKEP+XXfzQuUgPrbL33g+BuVpSLFS+/5De4aRefFOVw4hreqrgRp3m3Z9ivhMQ9/CNJsmm15NwnG4oy9I6326Fc2i6RajdQXekPC9IJbjKHOs8K4X0z7rphmQSaKphAfxVfKw5S3j+/GttrYx+FP/vLXLm0tEs2V5qcsxo1g="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "NwjG5wad9pIONGSNEGbTbOOGYWEh4qX1DIw4wnK2erF16II+B3MOnGsC/sO8LjHRnqTIIqEuTLO+Nx1RwPiHH0WRSY70QnG3ehvA7NCLOEvFj+vZxVJTbkZwKeJa678c7fcA8st/K/wJqv9BMXGljAtIoam+DeWipscrZBKV3zQlE1WKBJRF+ByoePmxrxutqbCP5tgUbHwkvUsuTe/j152dEcRI6qUwr7d+OtDDhvQfdQ52oWGtGXHs5Bxe2u23ZfbefLlf9cwmH/KybcvaGpS7YTBR/oyt49M9LGLUK1OqbqaG5uJTWwi6c0Q2/9kOXlMQ53RvCHTWIOPHKE/yTdKh2g/PPlCzJ6ioKaMmwwP266VkfRolMFK8qw6Nf/wwVM7hD92ZGdWdbCyXzw7kMkDlCYuE/ZpGAHJq/VnCly7e+0G153WBrZf/zg61ptsTy+Sh5D4Ao1+vRb1S5Ddigw6MUwSGWoinFl2wV+stRp/PHVe5MEAvXmxSLF52pB5HpPjhrxahMjlTaiDh18t/x4qyGUXaZ1kbDeueKAWK30t9VuDWB5AAGBb9GdGyhAy69vcfoM0tStMrpnGc3e29GQx85E46lnK1hc5cuDuu6KJ433VZX6kr+Lf8Y39ArwQm1oqe/vBWKyBPRbA3ZkJKKfgJKx1PAkVnQU5micqFP2o="

jobs:
  include:
    - stage: test
      script:
        - set -e
        - $SBT ++$TRAVIS_SCALA_VERSION test

    - stage: publish
      env:
      script:
        - set -e
        - $SBT transferPublishAndTagResources
        - TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/sbt-quasar-plugin'

      git:
        depth: false

after_success:
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
